# .gitlab-ci.yml

stages:
  - build
  - clmscan
  - upload_assets
  - site_deploy
  - environment

image:
  name: registry.aws.site.gs.com:443/dx/js-eng/nodejs-container-images/ubi-rhel20-node20-chrome:current
  pull_policy: never

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - node_modules/
    - .vite/

#──────────────────────────────────────────────────────────────────────────────
# TEMPLATE JOBS
#──────────────────────────────────────────────────────────────────────────────
.upload_assets: &upload_assets
  stage: upload_assets
  tags: [default, linux, kubernetes]
  script:
    - echo -e "\n📤 Uploading static assets from $STATIC_ASSETS"
    - ./scripts/upload-assets.sh "$STATIC_ASSETS"

.site_deploy: &site_deploy
  stage: site_deploy
  tags: [default, linux, kubernetes]
  script:
    - echo -e "\n🚀 Deploying to environment '$envIdentifier' (DID=$DID)"
    - ./scripts/deploy-site.sh \
        --config "$siteDeployConfigPath" \
        --did "$DID" \
        --env "$envIdentifier"

.create_environment: &create_env
  stage: environment
  tags: [default, linux, kubernetes]
  script:
    - echo -e "\n🌐 Creating environment '$environment[name]'"
    - ./scripts/environment-create.sh --id "$envIdentifier" --name "$environment[name]"

.stop_environment: &stop_env
  stage: environment
  tags: [default, linux, kubernetes]
  script:
    - echo -e "\n🛑 Stopping environment '$environment[name]'"
    - ./scripts/environment-stop.sh --id "$envIdentifier" --name "$environment[name]"


#──────────────────────────────────────────────────────────────────────────────
# 1) Build → lint, test, bundle, pack
#──────────────────────────────────────────────────────────────────────────────
build:
  stage: build
  tags: [default, linux, kubernetes]
  script:
    - echo -e "\n\033[1;33m➤ Installing dependencies (Node $(node -v))...\033[0m"
    - npm ci
    - echo -e "\n\033[1;34m=== 🔍 Linting Source Code ===\033[0m"
    - npm run lint
    - echo -e "\n\033[1;34m=== 🧪 Running Tests ===\033[0m"
    - npm run test -- --coverage --reporter jest-junit
    - echo -e "\n\033[1;34m=== 📦 Building Production Bundle ===\033[0m"
    - npm run build
    - echo -e "\033[1;32m✔ Build & tests complete!\033[0m"
    - npm pack
  artifacts:
    paths:
      - dist/
      - junit-report.xml
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^release-.*$/'
      changes:
        - "**/*"

#──────────────────────────────────────────────────────────────────────────────
# 2) CLM Scan (needs build)
#──────────────────────────────────────────────────────────────────────────────
request_clmscan:
  stage: clmscan
  tags: [default, linux, kubernetes]
  image: gitlab.registry.docker.site.gs.com:443/dx/sdlc-tools/gitlab-clm-plugin/gitlab-clm-plugin:current
  script:
    - /opt/clm/request-clmscan.sh "$CI_PROJECT_DIR/dist"
  needs:
    - build
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^release-.*$/'
      changes:
        - "**/*"

#──────────────────────────────────────────────────────────────────────────────
# 3) Upload Static Assets
#──────────────────────────────────────────────────────────────────────────────
static_assets:
  variables:
    STATIC_ASSETS: dist

upload_assets:
  <<: *upload_assets
  needs:
    - build
    - request_clmscan
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^release-.*$/'
      changes:
        - "**/*"

#──────────────────────────────────────────────────────────────────────────────
# 4) Site Deploy (feature & master branches)
#──────────────────────────────────────────────────────────────────────────────
site_deploy_feature:
  <<: *site_deploy
  variables:
    DID: 123456
    siteDeployConfigPath: "./siteDeployConfig.json"
    envIdentifier: "feature-branch"
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "master"'
      changes:
        - "**/*"
  when: manual
  needs:
    - upload_assets

site_deploy_master:
  <<: *site_deploy
  variables:
    DID: 654321
    siteDeployConfigPath: "./siteDeployConfig.json"
    envIdentifier: "master-branch"
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - "**/*"
  needs:
    - upload_assets

#──────────────────────────────────────────────────────────────────────────────
# 5) Dynamic Environments (create & stop)
#──────────────────────────────────────────────────────────────────────────────
environment_feature:
  <<: *create_env
  variables:
    envIdentifier: "feature-branch"
  environment:
    name: feature/$CI_COMMIT_REF_NAME
    on_stop: stop_environment_feature
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "master"'
      changes:
        - "**/*"

stop_environment_feature:
  <<: *stop_env
  variables:
    envIdentifier: "feature-branch"
  environment:
    name: feature/$CI_COMMIT_REF_NAME
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

environment_master:
  <<: *create_env
  variables:
    envIdentifier: "master-branch"
  environment:
    name: master/$CI_COMMIT_REF_NAME
    on_stop: stop_environment_master
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - "**/*"

stop_environment_master:
  <<: *stop_env
  variables:
    envIdentifier: "master-branch"
  environment:
    name: master/$CI_COMMIT_REF_NAME
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - "**/*"
